apiVersion: batch/v1
kind: Job
metadata:
  generateName: trigger-cd-pipeline-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: cd-pipeline-event-curl
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-d"
          - "payload={\"message\":\"start cd pipeline\"}"
          - "-H"
          - "'Content-Type: application/json'"
          - "http://localhost:12000/clover-cd-event"
      restartPolicy: Never
  backoffLimit: 20
